dataset: coco
coco_path: /usr/prakt/p028/data/COCO
masks: true
inst_segm: DefDETRInstanceSegTopK
top_k_inference: 40
fill_batch: false
batch_mode: false
attention_map_lvl: 1
lr: 0.0001
lr_drop: 15
epochs: 25
output_dir: /usr/prakt/p028/projects/results/Trackformer/experiment/out
resume: /usr/prakt/p028/projects/Trackformer/trackformer/models/r50_deformable_detr-checkpoint.pth
batch_size: 1
freeze_detr: true
debug: false
eval_only: false
aux_loss: false