dataset: coco
coco_path: /usr/prakt/p028/data/COCO
masks: true
inst_segm_module: DefDETRInstanceSegTopK
top_k_inference: 40
fill_batch: false
batch_mode: false
attention_map_lvl: 1
use_encoded_feats: false
lr: 0.0001
lr_drop: 15
epochs: 25
resume: /usr/prakt/p028/projects/Trackformer/trackformer/models/r50_deformable_detr-checkpoint.pth
freeze_detr: true
aux_loss: false